# Site settings
title: KnoxGearhead
email: knoxgearhead@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Everything you need to know about upcoming car events and happenings in Knoxville.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.knoxgearhead.com" # the base hostname & protocol for your site
twitter_username: knoxgearhead865
facebook_username: knoxgearhead
github_username:  knoxgearhead

# Build settings
markdown: kramdown
